// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/ubuntu/Dev/projects/ncnode/lib/clazz.js', ['ncnode.lib.clazz'], ['goog.array', 'goog.string']);
goog.addDependency('/home/ubuntu/Dev/projects/ncnode/lib/clazztests.js', [], ['goog.array', 'goog.testing.jsunit', 'ncnode.lib.clazz', 'ncnode.lib.type']);
goog.addDependency('/home/ubuntu/Dev/projects/ncnode/lib/deps.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/ncnode/lib/gencode.js', ['ncnode.lib.gencode'], ['goog.array', 'ncnode.lib.processor']);
goog.addDependency('/home/ubuntu/Dev/projects/ncnode/lib/processor.js', ['ncnode.lib.processor'], ['goog.array']);
goog.addDependency('/home/ubuntu/Dev/projects/ncnode/lib/type.js', ['ncnode.lib.type'], []);
goog.addDependency('/home/ubuntu/Dev/projects/ncnode/lib/typetests.js', [], ['goog.array', 'goog.testing.jsunit', 'ncnode.lib.type']);
